export const SET_VACATION = 'SET_VACATION';
export const ADD_VACATION = 'ADD_VACATION';
export const CHECK_VACATION = 'CHECK_VACATION';
export const SET_CHECKED_VACATION = 'SET_CHECKED_VACATION';
export const CHANGE_VACATION = 'CHANGE_VACATION';
export const DELETE_VACATION = 'DELETE_VACATION';
export const REST_DAYS = 'REST_DAYS';
